/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testgui;

/**
 *
 * @author fra
 */
public class Jprimes extends javax.swing.JFrame {

    /**
     * Creates new form Jprimes
     */
    public Jprimes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        mnb_MenuBar = new javax.swing.JMenuBar();
        mnu_FileSys = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnu_FSproduction = new javax.swing.JMenu();
        mnu_Calc = new javax.swing.JMenu();
        mnu_DB = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnu_FileSys.setText("FileSystem");
        mnu_FileSys.setToolTipText("Prime data on File System");
        mnu_FileSys.setVerifyInputWhenFocusTarget(false);

        jMenuItem2.setText("available FS threshold");
        mnu_FileSys.add(jMenuItem2);

        jMenuItem1.setText("Exit");
        jMenuItem1.setToolTipText("close the application");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseReleased(evt);
            }
        });
        mnu_FileSys.add(jMenuItem1);

        mnb_MenuBar.add(mnu_FileSys);

        mnu_FSproduction.setText("FileSystem data production");
        mnu_FSproduction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_FSproductionActionPerformed(evt);
            }
        });
        mnb_MenuBar.add(mnu_FSproduction);

        mnu_Calc.setText("Calculation");
        mnu_Calc.setToolTipText("");
        mnb_MenuBar.add(mnu_Calc);

        mnu_DB.setText("db");
        mnu_DB.setToolTipText("");
        mnb_MenuBar.add(mnu_DB);

        setJMenuBar(mnb_MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnu_FSproductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_FSproductionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnu_FSproductionActionPerformed

    private void jMenuItem1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseReleased
        // TODO add your handling code here:
        System.exit(0);// normal exit
    }//GEN-LAST:event_jMenuItem1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jprimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jprimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jprimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jprimes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jprimes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar mnb_MenuBar;
    private javax.swing.JMenu mnu_Calc;
    private javax.swing.JMenu mnu_DB;
    private javax.swing.JMenu mnu_FSproduction;
    private javax.swing.JMenu mnu_FileSys;
    // End of variables declaration//GEN-END:variables
}
