/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author fra
 */
public class frmJprime extends javax.swing.JFrame {

    /**
     * Creates new form frmJprime
     */
    public frmJprime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuStripTop = new javax.swing.JMenuBar();
        mnuTitleFileSystem = new javax.swing.JMenu();
        mnuItemExit = new javax.swing.JMenuItem();
        mnuTitleCalculation = new javax.swing.JMenu();
        mnuTitleDatabase = new javax.swing.JMenu();
        mnuTitle_msSql = new javax.swing.JMenu();
        mnuItem_msSql_enrichDB = new javax.swing.JMenuItem();
        mnuItem_msSql_stop = new javax.swing.JMenuItem();
        mnuTitle_postgreSql = new javax.swing.JMenu();
        mnuItem_postgreSql_enrichDB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuTitleFileSystem.setText("FileSystem");

        mnuItemExit.setText("Exit");
        mnuItemExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuItemExitMouseReleased(evt);
            }
        });
        mnuTitleFileSystem.add(mnuItemExit);

        mnuStripTop.add(mnuTitleFileSystem);

        mnuTitleCalculation.setText("Calculation");
        mnuStripTop.add(mnuTitleCalculation);

        mnuTitleDatabase.setText("Database");

        mnuTitle_msSql.setText("msSql");

        mnuItem_msSql_enrichDB.setText(" enrich DB");
        mnuTitle_msSql.add(mnuItem_msSql_enrichDB);

        mnuItem_msSql_stop.setText("DB calc stop");
        mnuTitle_msSql.add(mnuItem_msSql_stop);

        mnuTitleDatabase.add(mnuTitle_msSql);

        mnuTitle_postgreSql.setText("postgreSql");

        mnuItem_postgreSql_enrichDB.setText("enrich DB");
        mnuTitle_postgreSql.add(mnuItem_postgreSql_enrichDB);

        mnuTitleDatabase.add(mnuTitle_postgreSql);

        mnuStripTop.add(mnuTitleDatabase);

        setJMenuBar(mnuStripTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItemExitMouseReleased
        System.exit(0);// normal exit
    }//GEN-LAST:event_mnuItemExitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJprime().setVisible(true);
            }
        });
    }// main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mnuItemExit;
    private javax.swing.JMenuItem mnuItem_msSql_enrichDB;
    private javax.swing.JMenuItem mnuItem_msSql_stop;
    private javax.swing.JMenuItem mnuItem_postgreSql_enrichDB;
    private javax.swing.JMenuBar mnuStripTop;
    private javax.swing.JMenu mnuTitleCalculation;
    private javax.swing.JMenu mnuTitleDatabase;
    private javax.swing.JMenu mnuTitleFileSystem;
    private javax.swing.JMenu mnuTitle_msSql;
    private javax.swing.JMenu mnuTitle_postgreSql;
    // End of variables declaration//GEN-END:variables
}// class frmJprime
