/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author admin
 */
public class frmJprime extends javax.swing.JFrame {
    private Thread t;
    
    /**
     * Creates new form frmJprime
     */
    public frmJprime() {
        initComponents();
        this.t = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtClipboard = new javax.swing.JTextArea();
        mnuStripTop = new javax.swing.JMenuBar();
        mnuTitle_FileSystem = new javax.swing.JMenu();
        mnuItem_exit = new javax.swing.JMenuItem();
        mnuTitle_Calculation = new javax.swing.JMenu();
        mnuTitle_DB = new javax.swing.JMenu();
        mnuItem_enrichDB = new javax.swing.JMenuItem();
        mnuItem_stopDB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtClipboard.setColumns(20);
        txtClipboard.setRows(5);
        jScrollPane1.setViewportView(txtClipboard);

        mnuTitle_FileSystem.setText("FileSystem");

        mnuItem_exit.setText("Exit");
        mnuItem_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuItem_exitMouseReleased(evt);
            }
        });
        mnuTitle_FileSystem.add(mnuItem_exit);

        mnuStripTop.add(mnuTitle_FileSystem);

        mnuTitle_Calculation.setText("Calculation");
        mnuStripTop.add(mnuTitle_Calculation);

        mnuTitle_DB.setText("DataBase");

        mnuItem_enrichDB.setText("enrich DB");
        mnuItem_enrichDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuItem_enrichDBMouseReleased(evt);
            }
        });
        mnuTitle_DB.add(mnuItem_enrichDB);

        mnuItem_stopDB.setText("stop enriching DB");
        mnuItem_stopDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                mnuItem_stopDBMouseReleased(evt);
            }
        });
        mnuTitle_DB.add(mnuItem_stopDB);

        mnuStripTop.add(mnuTitle_DB);

        setJMenuBar(mnuStripTop);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItem_enrichDBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItem_enrichDBMouseReleased
        // TODO add your handling code here:
        Implementation.ITFORS1011_PostgreSql_Prime_INSERT_ primeInserter = new Implementation.ITFORS1011_PostgreSql_Prime_INSERT_(
                this.txtClipboard
        );
        // this.txtClipboard
        
        this.t = new Thread( primeInserter, "ITFORS1011_prime_insert" );// Fork
        synchronized (t){
        try
        {
            t.start();// thread start
            t.wait(5000);// milliseconds until it dies.
        }
        catch (InterruptedException e) 
        {
            System.out.println("background thread interrupted.");
            // close connection
            Thread.currentThread().interrupt(); 
        }
        }// synchro
    }//GEN-LAST:event_mnuItem_enrichDBMouseReleased

    private void mnuItem_stopDBMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItem_stopDBMouseReleased
        // TODO add your handling code here:  thread.interrupt();
        this.t.interrupt();
        this.txtClipboard.append("\n this.t.isAlive() "+ this.t.isAlive() );
    }//GEN-LAST:event_mnuItem_stopDBMouseReleased

    private void mnuItem_exitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuItem_exitMouseReleased
        System.exit(0);// normal exit
    }//GEN-LAST:event_mnuItem_exitMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJprime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJprime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuItem_enrichDB;
    private javax.swing.JMenuItem mnuItem_exit;
    private javax.swing.JMenuItem mnuItem_stopDB;
    private javax.swing.JMenuBar mnuStripTop;
    private javax.swing.JMenu mnuTitle_Calculation;
    private javax.swing.JMenu mnuTitle_DB;
    private javax.swing.JMenu mnuTitle_FileSystem;
    public javax.swing.JTextArea txtClipboard;
    // End of variables declaration//GEN-END:variables
}
