
--table
CREATE TABLE IF NOT EXISTS public.PrimeData
(
    ordinal bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    prime bigint NOT NULL,
    CONSTRAINT PrimeData_pkey PRIMARY KEY (ordinal,prime)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.PrimeData
    OWNER to postgres;


truncate  PrimeData RESTART IDENTITY;
select * from PrimeData;	

--------// usp_x_INSERT

CREATE OR REPLACE PROCEDURE public.usp_primedata_insert(
	IN par_prime bigint)
LANGUAGE 'plpgsql'
AS $BODY$
begin
insert into PrimeData(
    prime
  ) values(
par_prime );
commit;
end;
$BODY$;
ALTER PROCEDURE public.usp_primedata_insert(bigint)
    OWNER TO postgres;
